export const ROUTES = {
    HOME: '/home',
    HOME_ADMIN: '/home-admin',
    REGISTRO_USUARIO: '/registro-usuario',
    PRODUCTOS_ABM: '/productos-abm',
    INSUMOS_ABM: '/insumo-abm',
    PRODUCTOS: '/productos',
    LOGIN: '/login',
    STOCK_ABM: '/stock-abm',
    GESTION_EMPRESA: '/gestion-empresa',
    PROMOCIONES_ABM: '/promociones-abm',
    GESTION_SUCURSALES: '/gestion-sucursales',
    EMPRESA_ABM: '/empresa-abm',
    SUCURSAL_ABM: '/sucursal-abm',
    PRUEBA: '/prueba',
    ESTADO_PEDIDO: '/estado-pedido',
    COCINA: '/cocina',
};
